name: 'Pick Reviewer'

on:
  pull_request:
    types: opened

jobs:
  pick-random-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pick random reviewer
        id: pick_random_reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const core = require('@actions/core');

            const REVIEWER_COUNT = 1;

            const developers = JSON.parse(fs.readFileSync(`${{ github.workspace }}/.github/workflows/reviewer.json`));
            const prCreator = context.payload.pull_request.user.login;
            const prUrl = context.payload.pull_request.html_url;
            const prCreatorJson = developers.reviewers.find(person => person.githubName === prCreator);

            const teamHomepageMembers = developers.reviewers.filter((person) => person.team === "homepage" && person.githubName !== prCreator);
            const randomReviewers = getUniqueReviewers(teamHomepageMembers, REVIEWER_COUNT);
            if (!prCreatorJson) {
              setOutput(prCreator, prUrl, randomReviewers[0]);
            } else {
              setOutput(prCreatorJson.name, prUrl, randomReviewers[0]);
            }

            function getUniqueReviewers(reviewers, count) {
              const shuffled = reviewers.sort(() => 0.5 - Math.random());
              return shuffled.slice(0, count);
            }

            function setOutput(prCreator, prUrl, reviewer) {
              core.setOutput('writer', JSON.stringify(prCreator));
              core.setOutput('pullRequestLink', JSON.stringify(prUrl));
              core.setOutput('reviewer1Name', JSON.stringify(reviewer.name));
              core.setOutput('reviewer1GithubName', reviewer.githubName);
            }

      - name: test variable
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: console.log(${{ steps.pick_random_reviewer.outputs.reviewer1Name }})

      - name: Add Reviewer
        uses: madrapps/add-reviewers@v1
        with:
          reviewers: ${{ steps.pick_random_reviewer.outputs.reviewer1GithubName }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Slack Trigger
        run: |
          curl -X POST https://api-slack.internal.bcsdlab.com/api/review-request/frontend \
          -H 'Content-Type: application/json' \
          -d '{
                "pullRequestLink": ${{ steps.pick_random_reviewer.outputs.pullRequestLink }},
                "writer": ${{ steps.pick_random_reviewer.outputs.writer }},
                "reviewers": [${{ steps.pick_random_reviewer.outputs.reviewer1Name }}]
              }'
